PreCommit:
  RuboCop:
    enabled: true
    on_warn: warn
    required: true

CommitMsg:
  CapitalizedSubject:
    enabled: true
    on_warn: fail

  TrailingPeriod:
    enabled: true
    on_warn: fail

  TextWidth:
    enabled: true
    on_warn: fail

  SingleLineSubject:
    enabled: true
    on_warn: fail

TrailingWhitespace:
  enabled: true
