require 'i18n'
require 'yaml'

require_relative '../config/initializers/locale'

require 'bank_rg/accounts_manager'
require 'bank_rg/card'
require 'bank_rg/card/base_card'
require 'bank_rg/card/capitalist_card'
require 'bank_rg/card/usual_card'
require 'bank_rg/card/virtual_card'
require 'bank_rg/account'
require 'bank_rg/console/card_transactions'
require 'bank_rg/console/account_inputs'
require 'bank_rg/console/start_menu'
require 'bank_rg/console/card_menu'
require 'bank_rg/console/account_menu'
require 'bank_rg/console/main_menu'
require 'bank_rg/console'
